### ISSUE TITLE
Identify Bluetooth Module

### ISSUE THREAD

**Issue by jklein3** [half-spin/abies_pcb#3]
A Bluetooth module is needed to provide a wireless interface between the control app and the FPGA handling the digital filtering. For simplicity it will need to have a built in antenna.

Requirements:
- Built in antenna
- Up to date capabilities
- Pre-defined API
- Communication pathway to the FPGA

**Comment by jklein3** [comment]
The BGM13P32F512GA from Silicon Labs should provide everything necessary for the requirements: https://www.silabs.com/wireless/bluetooth/efr32bg13-series-1-modules/device.bgm13p32f512ga

Features include:
- Built in antenna
- I2S
- UART
- Up to +19 dBm TX power
- 25 GPIO pins
- 512 kB Flash

**Comment by fsodari** [comment]
I saw this on Silicon Labs: [BGX13](https://www.silabs.com/wireless/bluetooth/bgx13-wireless-xpress-modules) and a [starter kit](https://www.silabs.com/products/development-tools/wireless/bluetooth/bgx13p-bluetooth-xpress-starter-kit) for it. It looks pretty similar to the other one, but this one has a $20 kit instead of a $99 one. @jklein3 what do you think?

**Comment by jklein3** [comment]
@fsodari that looks great. Probably this one: https://www.silabs.com/wireless/bluetooth/bgx13-wireless-xpress-modules/device.bgx13p22ga.
- 8 GPIO pins
- UART for communication to FPGA
- Integrated antenna
- Well defined API
- OTA capabilities

**Comment by jklein3** [comment]
Evaluation board ordered.
